### Crear un nuevo usuario
POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "nombre": "Ana",
  "email": "ana@test.com"
}

### Obtener todos los usuarios
GET http://localhost:8080/usuarios

### Actualizar el usuario con ID 1
PUT http://localhost:8080/usuarios/11
Content-Type: application/json

{
  "nombre": "Manuel"
}

### Borrar el usuario con ID 1
DELETE http://localhost:8080/usuarios/1



### Crear una nueva publicacion
POST http://localhost:8080/publicaciones
Content-Type: application/json

{
  "titulo": "Mi Primera Publicacion",
  "contenido": "¡Hola Mundo desde Spring!",
  "usuarioId": 2
}

###Obtener todas las publicaciones
GET http://localhost:8080/publicaciones

###Obtener una Publicacion por ID
GET http://localhost:8080/publicaciones/2

###Actualizar una Publicacion
PUT http://localhost:8080/publicaciones/1
Content-Type: application/json

{
  "titulo": "Titulo Editado",
  "contenido": "Contenido actualizado."
}

###Borrar una Publicacion
DELETE http://localhost:8080/publicaciones/3